service: sample-app
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: app.handler
    url: true
plugins:
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes
